#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tf2-tools==0.17.1','console_scripts','view_frames'
__requires__ = 'tf2-tools==0.17.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tf2-tools==0.17.1', 'console_scripts', 'view_frames')()
    )
